local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05

  plugins:
   - {name: obstacle,  type: "costmap_2d::ObstacleLayer"}
   - {name: inflation, type: "costmap_2d::InflationLayer"}

  obstacle:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {data_type: LaserScan, topic: /scan, expected_update_rate: 0.25, marking: true, clearing: true}

  inflation:
    inflation_radius: 2.0
    cost_scaling_factor: 4.0
